steps:
- name: 'gcr.io/cloud-builders/docker'
  args: ['build',
         '-t',
         'gcr.io/$PROJECT_ID/cb-artifact-test',
         '.']
artifacts:
  objects:
    location: ['gs://cb-artifact-test']
    paths: ['/text/*.txt']

