steps:
- name: 'gcr.io/cloud-builders/docker'
  args: ['build',
         '-t',
         'gcr.io/$PROJECT_ID/cb-artifact-test',
         '.']
- name: 'gcr.io/$PROJECT_ID/cb-artifact-test'
  args: ['cp',
         '/build/*',
         '/workspace/']
- name: 'busybox'
  args: ['find', '/workspace']
artifacts:
  objects:
    location: 'gs://cb-artifact-test'
    paths: ['hello.*']