steps:
- name: 'gcr.io/cloud-builders/docker'
  args: ['build',
         '-t',
         'gcr.io/$PROJECT_ID/cb-artifact-test',
         '.']
- name: 'gcr.io/cloud-builders/docker'
  args: ['run',
         '--volume',
         '$PWD:/out'
         'gcr.io/$PROJECT_ID/cb-artifact-test',
         'cp',
         '/build/*',
         '/out/'
artifacts:
  objects:
    location: 'gs://cb-artifact-test'
    paths: ['*']