steps:
- name: 'gcr.io/cloud-builders/docker'
  args: ['build',
         '-t',
         'gcr.io/$PROJECT_ID/cb-artifact-test',
         '.']
- name: 'gcr.io/cloud-builders/docker'
  args: ['run',
         '--volume',
         '/workspace:/out',
         'gcr.io/$PROJECT_ID/cb-artifact-test',
         'cp', '-r',
         '/build/',
         '/out/']
artifacts:
  objects:
    location: 'gs://cb-artifact-test'
    paths: ['/build/*']